### ISSUE TITLE
Configuring the Rust toolchain

### ISSUE THREAD

**Issue by louisabricot** [louisabricot/gbmu#1]
Create a project directory using cargo and configure it to automatically build and load dependencies.
### Related issues:
- [x] https://github.com/louisabricot/gbmu/issues/2
- [x] https://github.com/louisabricot/gbmu/issues/3
- [x] https://github.com/louisabricot/gbmu/issues/4
- [x] https://github.com/louisabricot/gbmu/issues/5
