### ISSUE TITLE
Configure github-workflow

### ISSUE THREAD

**Issue by louisabricot** [louisabricot/gbmu#6]
- [x] Lock for push main branch and dev branch
- [x] Enable mandatory reviewing before accepting a PR
- [ ] Create github hooks and link to https://github.com/louisabricot/gbmu/issues/5
